export const AnalyticsEvents = {
  LANDING_PAGE_VIEW: "landing_page_view",
  LANDING_CREATOR_LEARN_MORE_CLICK: "landing_creator_learn_more_click",
  LANDING_BRAND_LEARN_MORE_CLICK: "landing_brand_learn_more_click",
  LOGIN_BUTTON_CLICK: "login_button_click",
  REGISTER_BUTTON_CLICK: "register_button_click",
  CAMPAIGN_LIST_VIEW: "campaign_list_view",
  CAMPAIGN_CARD_CLICK: "campaign_card_click",
  CAMPAIGN_VIEW: "campaign_view",
  CAMPAIGN_REGISTER_CLICK: "campaign_register_click",
  CAMPAIGN_REGISTER_SUCCESS: "campaign_register_success",
  CAMPAIGN_REGISTER_FAILED: "campaign_register_failed",
  CREATOR_PAGE_VIEW: "creator_page_view",
  BRAND_PAGE_VIEW: "brand_page_view",
  CREATOR_REGISTER_CLICK: "creator_register_click",
  BRAND_REGISTER_CLICK: "brand_register_click",
  CAMPAIGN_CREATE_CLICK: "campaign_create_click",
  CREATOR_APPLY_JOB_CLICK: "creator_apply_job_click",
  CREATOR_LANDING_VIEW: "creator_landing_view",
  CREATOR_UPGRADE_CLICK: "creator_upgrade_click",
  CREATOR_UPGRADE_SUBMIT: "creator_upgrade_submit",
  CREATOR_UPGRADE_SUCCESS: "creator_upgrade_success",
  CREATOR_UPGRADE_FAILED: "creator_upgrade_failed",
  MISSION_ACCEPT: "mission_accept",
  MISSION_SUBMIT: "mission_submit",
  MISSION_SUBMIT_SUCCESS: "mission_submit_success",
  MISSION_SUBMIT_FAILED: "mission_submit_failed",
  BRAND_LANDING_VIEW: "brand_landing_view",
  BRAND_UPGRADE_CLICK: "brand_upgrade_click",
  BRAND_UPGRADE_SUBMIT: "brand_upgrade_submit",
  BRAND_UPGRADE_SUCCESS: "brand_upgrade_success",
  BRAND_UPGRADE_FAILED: "brand_upgrade_failed",
  BRAND_CAMPAIGN_CREATE_OPEN: "brand_campaign_create_open",
  BRAND_CAMPAIGN_CREATE_SUBMIT: "brand_campaign_create_submit",
  BRAND_CAMPAIGN_CREATE_SUCCESS: "brand_campaign_create_success",
  BRAND_CAMPAIGN_CREATE_FAILED: "brand_campaign_create_failed",
  BRAND_CREATE_CAMPAIGN_SUCCESS: "brand_create_campaign_success",
  CREATOR_APPLY_JOB_SUCCESS: "creator_apply_job_success",
  CREATOR_JOB_APPROVED: "creator_job_approved",
  CREATOR_JOB_REJECTED: "creator_job_rejected",
  CREATOR_SUBMIT_PROOF_SUCCESS: "creator_submit_proof_success",
  PROOF_APPROVED: "proof_approved",
  PROOF_REJECTED: "proof_rejected",
  ORDER_SUCCESS: "order_success",
  CREATOR_COMMISSION_GENERATED: "creator_commission_generated",
  VOUCHER_USED: "voucher_used",
  LOGIN_PAGE_VIEW: "login_page_view",
  LOGIN: "login",
  LOGIN_SUCCESS: "login_success",
  LOGIN_FAILED: "login_failed",
  REGISTER_PAGE_VIEW: "register_page_view",
  SIGN_UP: "sign_up",
  REGISTER_SUCCESS: "register_success",
  REGISTER_FAILED: "register_failed",
  ROLE_REGISTER_SUCCESS: "role_register_success",
  CREATOR_REGISTER_SUCCESS: "creator_register_success",
  BRAND_REGISTER_SUCCESS: "brand_register_success",
  USER_SETTINGS_VIEW: "user_settings_view",
  PROFILE_UPDATE_SUCCESS: "profile_update_success",
  PROFILE_UPDATE_FAILED: "profile_update_failed",
  AVATAR_UPLOAD_SUBMIT: "avatar_upload_submit",
  AVATAR_UPLOAD_SUCCESS: "avatar_upload_success",
  AVATAR_UPLOAD_FAILED: "avatar_upload_failed",
  PHONE_UPDATE_SUCCESS: "phone_update_success"
} as const;

export type AnalyticsEventName = (typeof AnalyticsEvents)[keyof typeof AnalyticsEvents];

export const DCREATOR_ANALYTICS_EVENTS = {
  CAMPAIGN_REQUEST_CREATED: "campaign_request_created",
  CAMPAIGN_REQUEST_APPROVED: "campaign_request_approved",
  CAMPAIGN_CREATED: "campaign_created",
  CAMPAIGN_PUBLISHED: "campaign_published",
  CAMPAIGN_COMPLETED: "campaign_completed",
  CREATOR_APPLICATION_SUBMITTED: "creator_application_submitted",
  CREATOR_APPLICATION_APPROVED: "creator_application_approved",
  CREATOR_APPLICATION_REJECTED: "creator_application_rejected",
  CREATOR_MISSION_ASSIGNED: "creator_mission_assigned",
  CREATOR_MISSION_ACCEPTED: "creator_mission_accepted",
  CREATOR_MISSION_DECLINED: "creator_mission_declined",
  CREATOR_PROOF_SUBMITTED: "creator_proof_submitted",
  CREATOR_PROOF_APPROVED: "creator_proof_approved",
  CREATOR_PROOF_REJECTED: "creator_proof_rejected",
  CREATOR_REWARD_CREDITED: "creator_reward_credited",
  CREATOR_PAYOUT_REQUESTED: "creator_payout_requested",
  CREATOR_PAYOUT_PAID: "creator_payout_paid",
  PAYMENT_SUCCEEDED: "payment_succeeded",
  PAYMENT_FAILED: "payment_failed",
  ANALYTICS_DASHBOARD_VIEWED: "analytics_dashboard_viewed",
  ANALYTICS_CSV_EXPORTED: "analytics_csv_exported"
} as const;

export type DcreatorAnalyticsEventName =
  (typeof DCREATOR_ANALYTICS_EVENTS)[keyof typeof DCREATOR_ANALYTICS_EVENTS];
